name: S3 Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy_s3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS S3 Sync Action
        uses: awact/s3-action@0.1.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: us-west-1
          SOURCE_DIR: src
